oceanprotocol/DAOBot

src/gsheets/sync_gsheets_active_proposal_votes_snapshot.js, src/snapshot/snapshot_utils.js
This PR updates the voting strategies to include the latest w/ updates to account for: Uniswap V2 + Sushiswap + Bancor
=> Updating snapshot configuration to support uniswap, sushiswap, bancor.

cron_sync_votes_airtable.sh, cron_sync_votes_gsheets.sh, cron_update_funding_round.sh, package-lock.json, package.json, src/airtable/process_airtable_new_proposals.js, src/airtable/proposals/proposal_standings.js, src/airtable/sync_airtable_active_proposal_votes_snapshot.js, src/airtable/sync_airtable_all_proposal_votes_snapshot.js, src/scripts/update_funding_round.js, src/snapshot/prepare_snapshot_received_proposals_airtable.js, src/snapshot/snapshot_utils.js, src/test/airtable/test_airtable_proposal_standings.js, src/test/scripts/test_update_funding_round.js, src/test/snapshot/test_snapshot_graphql.js, src/test/test_schema.js
- update `snapshot_utils` to return a json format response from snapshot GQL URL;
- update `getActiveProposalVotes`.
=> Update Snapshot GraphQL

src/functions/chainlink.js, src/scripts/update_funding_round.js, src/test/test_get_token_price.js, src/utils/aggregatorV3InterfaceABI.json
Fixes #13 .
- Fetch price from Chainlink Data Feed
=> Fetching ocean price from chainlink

src/airtable/rounds/funding_rounds.js, src/scripts/update_funding_round.js, src/test/airtable/test_airtable_current_round.js, src/test/scripts/test_update_funding_round.test.js
Fixes #22  .
- update funding to be based on OCEAN
=> Update funding to be based on OCEAN

src/airtable/rounds/funding_rounds.js
Closes #37 .
- Updated calculateWinningProposalsForEarmark to be based off selected currency
=> Updated calculateWinningProposalsForEarmark to be based off selected currency

README.md, cron_update_standings.sh, src/airtable/process_airtable_all_proposal_standings.js, src/scripts/update_funding_round.js
Closes #53
- Converted the `main` function to the `processAirtableProposalStandings` function in the `process_airtable_all_proposal_standings.js` file and exported it.
- Calling `processAirtableProposalStandings` function inside `update_funding_round.js` if the current round is not `undefined`.
=> Merge `update_funding_round` & `update_standings`

src/airtable/process_airtable_funding_round_complete.js, src/scripts/update_funding_round.js
Fixes #51 
- display last round's burned funds in 'Funding Rounds' table
=> Display last round's burned funds in 'Funding Rounds' table

src/airtable/airtable_utils.js, src/airtable/process_airtable_all_proposal_standings.js, src/airtable/process_airtable_funding_round_complete.js, src/airtable/process_airtable_new_proposals.js, src/airtable/proposals/proposal_standings.js, src/airtable/rounds/funding_rounds.js, src/airtable/sync_airtable_active_proposal_votes_snapshot.js, src/airtable/sync_airtable_all_proposal_votes_snapshot.js, src/functions/chainlink.js, src/functions/coingecko.js, src/gsheets/gsheets_utils.js, src/gsheets/index.js, src/gsheets/sync_gsheets_active_proposal_votes_snapshot.js, src/scripts/update_funding_round.js, src/snapshot/prepare_snapshot_received_proposals_airtable.js, src/snapshot/snapshot_utils.js, src/snapshot/submit_snapshot_accepted_proposals_airtable.js, src/test/airtable/test_airtable_round_winners.test.js, src/test/snapshot/test_snapshot_graphql.test.js, src/test/test_create_wallet.js, src/test/test_get_ocean_balance.js, src/test/test_get_token_price.js, src/test/test_load_wallet.js, src/test/test_schema.js, src/test/test_snapshot_calcBlockHeight.js, src/test/test_snapshot_scores.js, src/utils/logger.js
Closes #46.
- Created `logger.js`.
- Replaced all `console.log`s with the custom logger function.
- Logger won't log when the `GACTIONS_ENV` env variable is defined (it will be defined in Github actions) and the log type is not `error`.
=> Create custom logger

src/airtable/project_summary.js, src/test/airtable/test_airtable_current_round.test.js, src/test/airtable/test_project_summary.test.js, src/test/scripts/test_update_funding_round.test.js, src/test/snapshot/test_snapshot_graphql.test.js
=> Add Airtable for testing, make all test run

src/airtable/process_airtable_funding_round_complete.js, src/airtable/proposals/proposal_standings.js
Fixes #40 .
- add a new proposal state for projects that want to withdraw
- exclude withdrawn projects from compute winning proposals
- exclude withdrawn projects from compute burned funds
=> Add a new proposal state for projects that want to withdraw

package.json, src/airtable/proposals/proposal_standings.js, src/test/airtable/test_airtable_proposal_standings.test.js, src/test/airtable/test_airtable_sync.test.js, src/test/airtable/test_project_summary.test.js, src/test/snapshot/test_snapshot_graphql.test.js, src/utils/logger.js
Closes #66 .
- Enriching and refactoring the tests
=> Improve test coverage

src/airtable/process_airtable_funding_round_complete.js
=> Dump Round Winners to GSheet grouped by Earmark

src/gsheets/sync_gsheets_active_proposal_votes_snapshot.js
Fixes #91.
- Increase the vote count by 1 for each vote.
- Get ipfsHash from the first proposal. There is no need to loop through all proposals. `ipfsHash` is always the same for that round.
=> R13 bug: Some big numbers being spat out for #Num Votes & #Num Yes

src/airtable/rounds/funding_rounds.js, src/test/airtable/test_airtable_round_winners.test.js
Fixes #14 .
- Voting edge case `YesVotes === NoVotes` addressed
- fix test impacted by the above change
=> Voting edge case

src/utils/logger.js
Fixes #110 .
- Logger logs each argument.
- 
-
=> Logger should log multiple arguments

src/airtable/process_airtable_funding_round_complete.js, src/airtable/rounds/funding_rounds.js, src/test/airtable/test_airtable_round_winners.test.js
=> Implement burn&recycle switches

src/scripts/ops/generate_issues.js, src/utils/ops/repeatable_tasks.json
=> Improve Ops Tasks

src/airtable/process_airtable_funding_round_complete.js, src/gsheets/sync_gsheets_active_proposal_votes_snapshot.js, src/scripts/update_funding_round.js, src/snapshot/prepare_snapshot_received_proposals_airtable.js
Please see issues:
https://github.com/oceanprotocol/DAOBot/issues/116
https://github.com/oceanprotocol/DAOBot/issues/115
=> Updated prepare_proposals_for_snapshot() so I could deploy R13

src/gsheets/sync_gsheets_active_proposal_votes_snapshot.js, src/scripts/update_funding_round.js, src/test/gsheets/test_gsheets_sync.test.js
=> Generate Round Results GSheet before voting period starts

src/snapshot/prepare_snapshot_received_proposals_airtable.js
Fixes #132 .
- Fix outdated function `prepareProposalsForSnapshot`
- 
-
=> Fix outdated function `prepareProposalsForSnapshot`

src/airtable/proposals/proposal_standings.js
Fixes #130 .
- Set the proposal to Rejected if no wallet address is provided
- 
-
=> Set the proposal to Rejected if no wallet address is provided

src/airtable/proposals/proposal_standings.js
Fixes #134  .
- Set `Reason Rejected` to `Valid Proposal` if the proposal is valid.
=> Set to `Valid Proposal` if valid

src/snapshot/snapshot_utils.js
=> Update QV strategy params

src/airtable/sync_airtable_active_proposal_votes_snapshot.js, src/airtable/sync_airtable_all_proposal_votes_snapshot.js, src/gsheets/sync_gsheets_active_proposal_votes_snapshot.js, src/scripts/update_funding_round.js, src/snapshot/snapshot_utils.js, src/test/snapshot/test_snapshot_graphql.test.js
=> Fix QF calculations

.dockerignore, Dockerfile, app.js, cron_project_summary.sh, package-lock.json, package.json, src/scripts/update_funding_round.js
- Dockerizing
- Set up `croner` package
=> Staging daobot

src/airtable/project_summary.js, src/scripts/update_funding_round.js, src/test/airtable/test_airtable_proposal_standings.test.js
Fixes tests that were failing due to earmark updates.
=> Revert 154 feature/update project summary from main, and merge into staging.

package-lock.json, package.json, src/airtable/process_airtable_all_proposal_standings.js, src/airtable/proposals/proposal_standings.js, src/snapshot/prepare_snapshot_received_proposals_airtable.js, src/snapshot/snapshot_utils.js
Fixes #124 .
- Provide multi-chain support for 500 OCEAN required to submit a proposal.
- Only check Ocean balances for the current round
- Check balances every 15 minutes
=> Provide multi-chain support for 500 OCEAN required to submit a proposal

src/airtable/rounds/funding_rounds.js, src/snapshot/snapshot_utils.js, src/test/airtable/test_airtable_round_15.test.js, src/test/airtable/test_airtable_round_winners.test.js
=> QF distribution

src/scripts/update_funding_round.js
=> Fix Round Results sheet creation in DD period

src/airtable/sync_airtable_active_proposal_votes_snapshot.js, src/airtable/sync_airtable_all_proposal_votes_snapshot.js, src/scripts/update_funding_round.js, src/snapshot/snapshot_utils.js
=> Fix GSheet votes not updating in voting period

src/airtable/sync_airtable_active_proposal_votes_snapshot.js
=> Exclude withdrawn proposals from GSheet Round Results

src/utils/ops/repeatable_tasks.json
=> Change recursive issues assignees

update_funding_cron.js
=> Fix DAOBot gets stuck when there is an error

src/airtable/rounds/funding_rounds.js, src/test/airtable/test_airtable_current_round.test.js, src/test/airtable/test_airtable_round_winners.test.js
=> Integrate 2nd/3rd Grant Earmark 

src/scripts/update_funding_round.js
Fixes #207 
- Automatically adjust the funding available to be minimum $100k
=> Automatically adjust to minimum $100k

src/scripts/update_funding_round.js
Updated logic to also adjust ['Funding Available'] (OCEAN amount)
=> Updated logic to also update Funding Available (OCEAN)

src/airtable/rounds/funding_rounds.js, src/scripts/update_funding_round.js
- Fix floor bug.
- Set the floor to $75k. 
- Code formatting.
=> Fix floor bug
